### ISSUE TITLE
bug in download image 

### ISSUE THREAD

**Issue by ahmedshalabii** [amit-y11/PicSplash#4]
downloadImage() async {
    final status = await Permission.storage.request();
    var dir = Directory("/sdcard/PicSplash");
    if (!await dir.exists()) {
      await dir.create(recursive: true);
    }
    if (status.isGranted) {
      await FlutterDownloader.enqueue(
        url: widget.images.urls.full,
        savedDir: dir.path,
        fileName: 'image_${widget.images.id}.jpg',
      );
    } else {
      await Permission.storage.request();
    }
  }

**Comment by amit-y11** [comment]
can you please elaborate , what's the bug here
