### ISSUE TITLE
when we try to download or set wallpaper from 'favorites' its not working

### ISSUE THREAD

**Issue by NomanBaigA** [amit-y11/PicSplash#5]
1> This is the error when I download images from favorite....

W/WM-WorkSpec( 2604): Backoff delay duration less than minimum value
I/flutter ( 2604): 0
I/flutter ( 2604): -1
W/System.err( 2604): java.net.MalformedURLException: no protocol: 
W/System.err( 2604): 	at java.net.URL.<init>(URL.java:601)
W/System.err( 2604): 	at java.net.URL.<init>(URL.java:498)
W/System.err( 2604): 	at java.net.URL.<init>(URL.java:447)
W/System.err( 2604): 	at vn.hunghd.flutterdownloader.DownloadWorker.downloadFile(DownloadWorker.java:273)
W/System.err( 2604): 	at vn.hunghd.flutterdownloader.DownloadWorker.doWork(DownloadWorker.java:203)
W/System.err( 2604): 	at androidx.work.Worker$1.run(Worker.java:85)
W/System.err( 2604): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
W/System.err( 2604): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
W/System.err( 2604): 	at java.lang.Thread.run(Thread.java:923)
I/WM-WorkerWrapper( 2604): Worker result SUCCESS for Work [ id=42f5424f-cf89-48f4-9a0a-8c0325607639, tags={ flutter_download_task, vn.hunghd.flutterdownloader.DownloadWorker } ]

2> This is the error when I set wallpaper from favorite....

E/flutter ( 2604): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: Invalid argument(s): No host specified in URI 
E/flutter ( 2604): #0      _HttpClient._openUrl (dart:_http/http_impl.dart:2662:9)
E/flutter ( 2604): #1      _HttpClient.openUrl (dart:_http/http_impl.dart:2568:7)
E/flutter ( 2604): #2      IOClient.send (package:http/src/io_client.dart:30:38)
E/flutter ( 2604): #3      HttpFileService.get (package:flutter_cache_manager/src/web/file_service.dart:35:44)
E/flutter ( 2604): #4      WebHelper._download (package:flutter_cache_manager/src/web/web_helper.dart:117:24)
E/flutter ( 2604): #5      WebHelper._updateFile (package:flutter_cache_manager/src/web/web_helper.dart:99:28)
E/flutter ( 2604): <asynchronous suspension>
E/flutter ( 2604): #6      WebHelper._downloadOrAddToQueue (package:flutter_cache_manager/src/web/web_helper.dart:67:7)
E/flutter ( 2604): <asynchronous suspension>
E/flutter ( 2604):

**Comment by amit-y11** [comment]
issue resolved.
